<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CRM" nsURI="http://cs.gssi.it/CRM" nsPrefix="crm">
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crm" lowerBound="1" eType="#//CRM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Worker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crm" lowerBound="1" eType="#//CRM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="company" lowerBound="1"
        eType="#//Company" eOpposite="#//Company/workers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalWorker" eSuperTypes="#//Worker"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalWorker" eSuperTypes="#//Worker"/>
  <eClassifiers xsi:type="ecore:EClass" name="CRM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Worker" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="-1"
        eType="#//Client" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Company">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workers" upperBound="-1"
        eType="#//Worker" eOpposite="#//Worker/company"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CRMModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crm" eType="#//CRM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Company" eType="#//Company"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
